name: Build package, documentation, and test coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v3.3.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven
        run: mvn package
      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            client/target/
            server/target/
      - name: Upload the documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation-artifact
          path: |
            client/target/apidocs/
            server/target/apidocs/
      - name: Upload the test coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-artifact
          path: |
            client/target/site/jacoco/
            server/target/site/jacoco/
